[rospy.client][INFO] 2020-07-02 13:09:56,457: init_node, name[/robot2/urdf_spawner], pid[7657]
[xmlrpc][INFO] 2020-07-02 13:09:56,458: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-07-02 13:09:56,459: Started XML-RPC server [http://177b797fd17c:44693/]
[rospy.init][INFO] 2020-07-02 13:09:56,459: ROS Slave URI: [http://177b797fd17c:44693/]
[rospy.impl.masterslave][INFO] 2020-07-02 13:09:56,459: _ready: http://177b797fd17c:44693/
[rospy.registration][INFO] 2020-07-02 13:09:56,461: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-07-02 13:09:56,461: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-07-02 13:09:56,560: registered with master
[rospy.rosout][INFO] 2020-07-02 13:09:56,560: initializing /rosout core topic
[rospy.rosout][INFO] 2020-07-02 13:09:56,562: connected to core topic /rosout
[rospy.simtime][INFO] 2020-07-02 13:09:56,564: initializing /clock core topic
[rospy.simtime][INFO] 2020-07-02 13:09:56,573: connected to core topic /clock
[rospy.internal][INFO] 2020-07-02 13:09:56,580: topic[/clock] adding connection to [http://177b797fd17c:45951/], count 0
[rosout][INFO] 2020-07-02 13:09:56,587: Loading model XML from ros parameter
[rosout][INFO] 2020-07-02 13:09:56,598: Waiting for service /gazebo/spawn_urdf_model
[rosout][INFO] 2020-07-02 13:09:56,600: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2020-07-02 13:09:56,827: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2020-07-02 13:10:51,664: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-07-02 13:10:51,667: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-07-02 13:10:51,667: topic[/clock] removing connection to http://177b797fd17c:45951/
[rospy.impl.masterslave][INFO] 2020-07-02 13:10:51,668: signal-2
[rospy.internal][WARNING] 2020-07-02 13:10:51,668: Unknown error initiating TCP/IP socket to 177b797fd17c:55931 (http://177b797fd17c:45951/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][ERROR] 2020-07-02 13:10:52,283: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 4] Interrupted system call

[rospy.core][INFO] 2020-07-02 13:10:52,284: signal_shutdown [atexit]
