[rospy.client][INFO] 2019-06-29 14:13:54,797: init_node, name[/mybot_spawn], pid[184]
[xmlrpc][INFO] 2019-06-29 14:13:54,797: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-29 14:13:54,797: Started XML-RPC server [http://dc5b429f784e:42333/]
[rospy.init][INFO] 2019-06-29 14:13:54,798: ROS Slave URI: [http://dc5b429f784e:42333/]
[rospy.impl.masterslave][INFO] 2019-06-29 14:13:54,798: _ready: http://dc5b429f784e:42333/
[xmlrpc][INFO] 2019-06-29 14:13:54,799: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-29 14:13:54,799: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-06-29 14:13:54,898: registered with master
[rospy.rosout][INFO] 2019-06-29 14:13:54,898: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-29 14:13:54,900: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-29 14:13:54,901: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-29 14:13:54,904: connected to core topic /clock
[rosout][INFO] 2019-06-29 14:13:54,908: Loading model XML from ros parameter
[rosout][INFO] 2019-06-29 14:13:54,913: Waiting for service /gazebo/spawn_urdf_model
[rosout][INFO] 2019-06-29 14:13:54,915: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2019-06-29 14:13:54,917: topic[/clock] adding connection to [http://dc5b429f784e:34125/], count 0
[rospy.internal][INFO] 2019-06-29 14:13:55,124: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2019-06-29 14:13:55,159: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2019-06-29 14:13:55,160: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-29 14:13:55,163: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-29 14:13:55,164: topic[/clock] removing connection to http://dc5b429f784e:34125/
[rospy.internal][WARNING] 2019-06-29 14:13:55,165: Unknown error initiating TCP/IP socket to dc5b429f784e:43513 (http://dc5b429f784e:34125/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2019-06-29 14:13:55,165: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2019-06-29 14:13:55,165: atexit
