[rospy.client][INFO] 2019-06-25 12:22:14,976: init_node, name[/rostopic_55129_1561465334863], pid[55129]
[xmlrpc][INFO] 2019-06-25 12:22:14,977: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 12:22:14,978: Started XML-RPC server [http://dc5b429f784e:44043/]
[rospy.init][INFO] 2019-06-25 12:22:14,979: ROS Slave URI: [http://dc5b429f784e:44043/]
[rospy.impl.masterslave][INFO] 2019-06-25 12:22:14,980: _ready: http://dc5b429f784e:44043/
[rospy.registration][INFO] 2019-06-25 12:22:14,981: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2019-06-25 12:22:14,981: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2019-06-25 12:22:15,080: registered with master
[rospy.rosout][INFO] 2019-06-25 12:22:15,081: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 12:22:15,083: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 12:22:15,089: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 12:22:15,095: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 12:22:15,100: topic[/clock] adding connection to [http://dc5b429f784e:42391/], count 0
[rospy.internal][INFO] 2019-06-25 12:22:15,146: topic[/map] adding connection to [http://dc5b429f784e:37205/], count 0
[rospy.internal][INFO] 2019-06-25 12:22:15,329: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 12:22:18,305: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-06-25 12:22:18,328: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 12:22:18,329: topic[/clock] removing connection to http://dc5b429f784e:42391/
[rospy.topics][ERROR] 2019-06-25 12:22:18,329: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2019-06-25 12:22:18,330: topic[/map] removing connection to http://dc5b429f784e:37205/
[rospy.impl.masterslave][INFO] 2019-06-25 12:22:18,330: signal-2
[rospy.internal][WARNING] 2019-06-25 12:22:18,331: Unknown error initiating TCP/IP socket to dc5b429f784e:51377 (http://dc5b429f784e:42391/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2019-06-25 12:22:18,835: signal_shutdown [signal-2]
[rospy.core][INFO] 2019-06-25 12:22:18,835: signal_shutdown [atexit]
