[rospy.client][INFO] 2019-06-25 13:31:40,586: init_node, name[/view_frames_72559_1561469500451], pid[72559]
[xmlrpc][INFO] 2019-06-25 13:31:40,594: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2019-06-25 13:31:40,596: ROS Slave URI: [http://dc5b429f784e:35593/]
[xmlrpc][INFO] 2019-06-25 13:31:40,596: Started XML-RPC server [http://dc5b429f784e:35593/]
[rospy.impl.masterslave][INFO] 2019-06-25 13:31:40,597: _ready: http://dc5b429f784e:35593/
[xmlrpc][INFO] 2019-06-25 13:31:40,604: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 13:31:40,605: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-06-25 13:31:40,697: registered with master
[rospy.rosout][INFO] 2019-06-25 13:31:40,697: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 13:31:40,701: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 13:31:40,703: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 13:31:40,707: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 13:31:40,726: topic[/clock] adding connection to [http://dc5b429f784e:39511/], count 0
[rospy.internal][INFO] 2019-06-25 13:31:40,731: topic[/tf] adding connection to [http://dc5b429f784e:39511/], count 0
[rospy.internal][INFO] 2019-06-25 13:31:40,734: topic[/tf] adding connection to [http://dc5b429f784e:36259/], count 1
[rospy.internal][INFO] 2019-06-25 13:31:40,739: topic[/tf] adding connection to [http://dc5b429f784e:38229/], count 2
[rospy.internal][INFO] 2019-06-25 13:31:40,942: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 13:31:45,842: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 13:31:45,856: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 13:31:45,857: topic[/clock] removing connection to http://dc5b429f784e:39511/
[rospy.internal][ERROR] 2019-06-25 13:31:45,859: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2019-06-25 13:31:45,859: Unknown error initiating TCP/IP socket to dc5b429f784e:40003 (http://dc5b429f784e:39511/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2019-06-25 13:31:45,860: topic[/tf] removing connection to http://dc5b429f784e:39511/
[rospy.internal][INFO] 2019-06-25 13:31:45,861: topic[/tf] removing connection to http://dc5b429f784e:36259/
[rospy.internal][INFO] 2019-06-25 13:31:45,862: topic[/tf] removing connection to http://dc5b429f784e:38229/
[rospy.internal][WARNING] 2019-06-25 13:31:45,863: Unknown error initiating TCP/IP socket to dc5b429f784e:46219 (http://dc5b429f784e:38229/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2019-06-25 13:31:45,864: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2019-06-25 13:31:45,865: atexit
