[rospy.client][INFO] 2019-06-25 13:48:04,652: init_node, name[/mybot_spawn], pid[75055]
[xmlrpc][INFO] 2019-06-25 13:48:04,653: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 13:48:04,654: Started XML-RPC server [http://dc5b429f784e:40617/]
[rospy.impl.masterslave][INFO] 2019-06-25 13:48:04,654: _ready: http://dc5b429f784e:40617/
[rospy.init][INFO] 2019-06-25 13:48:04,655: ROS Slave URI: [http://dc5b429f784e:40617/]
[xmlrpc][INFO] 2019-06-25 13:48:04,656: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 13:48:04,656: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-06-25 13:48:04,755: registered with master
[rospy.rosout][INFO] 2019-06-25 13:48:04,756: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 13:48:04,758: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 13:48:04,760: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 13:48:04,763: connected to core topic /clock
[rosout][INFO] 2019-06-25 13:48:04,766: Loading model XML from ros parameter
[rosout][INFO] 2019-06-25 13:48:04,769: Waiting for service /gazebo/spawn_urdf_model
[rosout][INFO] 2019-06-25 13:48:04,772: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2019-06-25 13:48:04,773: topic[/clock] adding connection to [http://dc5b429f784e:43795/], count 0
[rospy.internal][INFO] 2019-06-25 13:48:04,994: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2019-06-25 13:48:05,083: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2019-06-25 13:48:05,083: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 13:48:05,086: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 13:48:05,087: topic[/clock] removing connection to http://dc5b429f784e:43795/
[rospy.internal][WARNING] 2019-06-25 13:48:05,088: Unknown error initiating TCP/IP socket to dc5b429f784e:55353 (http://dc5b429f784e:43795/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2019-06-25 13:48:05,088: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2019-06-25 13:48:05,088: atexit
